"""init

Revision ID: 0b4cf0e12087
Revises: 
Create Date: 2026-08-31 17:54:57.624417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b4cf0e12087'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PROCENT', 'FIX', name='coupon_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('therapies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sessions_included', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RECEPTIE', 'CLIENT', name='role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='account_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('client_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('coupon_therapies',
    sa.Column('coupon_id', sa.String(), nullable=False),
    sa.Column('therapy_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'therapy_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('therapy_id', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PROGRAMATA', 'CONFIRMATA', 'ANULATA', 'FINALIZATA', name='appointment_status'), nullable=False),
    sa.Column('google_calendar_event_id', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('therapy_id', sa.String(), nullable=True),
    sa.Column('appointment_id', sa.String(), nullable=True),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_appointment_id'), 'medical_records', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_medical_records_client_id'), 'medical_records', ['client_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('therapy_id', sa.String(), nullable=False),
    sa.Column('coupon_id', sa.String(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('NEPLATIT', 'PARTIAL', 'PLATIT', name='payment_status'), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=True),
    sa.Column('package_total_sessions', sa.Integer(), nullable=True),
    sa.Column('sessions_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    # (Tabelele Prisma vechi, dacă mai există dintr-o rulare anterioară a
    # mitmed-portal, se șterg manual o singură dată — vezi README — nu mai
    # fac parte din această migrare, ca să rămână aplicabilă și pe o bază
    # de date complet nouă.)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Session',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Session_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Session_pkey'))
    )
    op.create_index(op.f('Session_userId_idx'), 'Session', ['userId'], unique=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.create_table('Therapy',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('durationMinutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('sessionsIncluded', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Therapy_pkey'))
    )
    op.create_table('ClientProfile',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fullName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('birthDate', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('emergencyContactName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emergencyContactPhone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('ClientProfile_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ClientProfile_pkey'))
    )
    op.create_index(op.f('ClientProfile_userId_key'), 'ClientProfile', ['userId'], unique=True)
    op.create_table('Coupon',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('PROCENT', 'FIX', name='CouponType'), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('validFrom', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('validUntil', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('maxUses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usesCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Coupon_pkey'))
    )
    op.create_index(op.f('Coupon_code_key'), 'Coupon', ['code'], unique=True)
    op.create_table('Payment',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('clientId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('therapyId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('couponId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('basePrice', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('discountAmount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('finalPrice', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('NEPLATIT', 'PARTIAL', 'PLATIT', name='PaymentStatus'), server_default=sa.text('\'NEPLATIT\'::"PaymentStatus"'), autoincrement=False, nullable=False),
    sa.Column('method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('paidAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('appointmentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('packageTotalSessions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sessionsUsed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointmentId'], ['Appointment.id'], name=op.f('Payment_appointmentId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clientId'], ['ClientProfile.id'], name=op.f('Payment_clientId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['couponId'], ['Coupon.id'], name=op.f('Payment_couponId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['therapyId'], ['Therapy.id'], name=op.f('Payment_therapyId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('Payment_pkey'))
    )
    op.create_index(op.f('Payment_clientId_idx'), 'Payment', ['clientId'], unique=False)
    op.create_index(op.f('Payment_appointmentId_key'), 'Payment', ['appointmentId'], unique=True)
    op.create_table('Appointment',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('clientId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('therapyId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('startsAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PROGRAMATA', 'CONFIRMATA', 'ANULATA', 'FINALIZATA', name='AppointmentStatus'), server_default=sa.text('\'PROGRAMATA\'::"AppointmentStatus"'), autoincrement=False, nullable=False),
    sa.Column('googleCalendarEventId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdById', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clientId'], ['ClientProfile.id'], name=op.f('Appointment_clientId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapyId'], ['Therapy.id'], name=op.f('Appointment_therapyId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('Appointment_pkey'))
    )
    op.create_index(op.f('Appointment_startsAt_idx'), 'Appointment', ['startsAt'], unique=False)
    op.create_index(op.f('Appointment_clientId_idx'), 'Appointment', ['clientId'], unique=False)
    op.create_table('_CouponTherapies',
    sa.Column('A', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('B', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['A'], ['Coupon.id'], name=op.f('_CouponTherapies_A_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['B'], ['Therapy.id'], name=op.f('_CouponTherapies_B_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('A', 'B', name=op.f('_CouponTherapies_AB_pkey'))
    )
    op.create_index(op.f('_CouponTherapies_B_index'), '_CouponTherapies', ['B'], unique=False)
    op.create_table('MedicalRecord',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('clientId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('authorId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('therapyId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sessionDate', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('appointmentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointmentId'], ['Appointment.id'], name=op.f('MedicalRecord_appointmentId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['authorId'], ['User.id'], name=op.f('MedicalRecord_authorId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['clientId'], ['ClientProfile.id'], name=op.f('MedicalRecord_clientId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapyId'], ['Therapy.id'], name=op.f('MedicalRecord_therapyId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('MedicalRecord_pkey'))
    )
    op.create_index(op.f('MedicalRecord_clientId_idx'), 'MedicalRecord', ['clientId'], unique=False)
    op.create_index(op.f('MedicalRecord_appointmentId_idx'), 'MedicalRecord', ['appointmentId'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('passwordHash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'RECEPTIE', 'CLIENT', name='Role'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', name='AccountStatus'), server_default=sa.text('\'ACTIVE\'::"AccountStatus"'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('User_pkey'))
    )
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.create_table('AuditLog',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('actorId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('targetType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('targetId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actorId'], ['User.id'], name=op.f('AuditLog_actorId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('AuditLog_pkey'))
    )
    op.create_index(op.f('AuditLog_targetType_targetId_idx'), 'AuditLog', ['targetType', 'targetId'], unique=False)
    op.create_index(op.f('AuditLog_actorId_idx'), 'AuditLog', ['actorId'], unique=False)
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_medical_records_client_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_appointment_id'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('sessions')
    op.drop_table('coupon_therapies')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('therapies')
    op.drop_table('coupons')
    # ### end Alembic commands ###
