"""medical record treatment plan

Revision ID: 1fa09dba1896
Revises: f88de4d07461
Create Date: 2026-09-02 10:06:51.791029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa09dba1896'
down_revision: Union[str, Sequence[str], None] = 'f88de4d07461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('treatment_plan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'treatment_plan')
    # ### end Alembic commands ###
