"""reminders, consents, public booking, medical history, body map

Revision ID: 673f5a6a4e82
Revises: 0b4cf0e12087
Create Date: 2026-08-31 20:00:44.246509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673f5a6a4e82'
down_revision: Union[str, Sequence[str], None] = '0b4cf0e12087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_booking_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('therapy_id', sa.String(), nullable=True),
    sa.Column('preferred_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOU', 'CONFIRMAT', 'RESPINS', name='booking_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('version_text', sa.String(), nullable=False),
    sa.Column('signature_data_url', sa.String(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_client_id'), 'consents', ['client_id'], unique=False)
    op.add_column('appointments', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('client_profiles', sa.Column('medical_history', sa.JSON(), nullable=True))
    op.add_column('medical_records', sa.Column('body_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'body_map')
    op.drop_column('client_profiles', 'medical_history')
    op.drop_column('appointments', 'reminder_sent_at')
    op.drop_index(op.f('ix_consents_client_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_table('public_booking_requests')
    # ### end Alembic commands ###
