"""therapy packages

Revision ID: b7e4cd26d15c
Revises: 1fa09dba1896
Create Date: 2026-09-02 19:46:05.363873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e4cd26d15c'
down_revision: Union[str, Sequence[str], None] = '1fa09dba1896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapy_packages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('therapy_id', sa.String(), nullable=False),
    sa.Column('sessions_included', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['therapy_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapy_id'], ['therapies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_items_package_id'), 'package_items', ['package_id'], unique=False)
    op.add_column('payments', sa.Column('package_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('package_purchase_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_package_id'), 'payments', ['package_id'], unique=False)
    op.create_index(op.f('ix_payments_package_purchase_id'), 'payments', ['package_purchase_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'therapy_packages', ['package_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_package_purchase_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_package_id'), table_name='payments')
    op.drop_column('payments', 'package_purchase_id')
    op.drop_column('payments', 'package_id')
    op.drop_index(op.f('ix_package_items_package_id'), table_name='package_items')
    op.drop_table('package_items')
    op.drop_table('therapy_packages')
    # ### end Alembic commands ###
