"""consent types and templates

Revision ID: f88de4d07461
Revises: 673f5a6a4e82
Create Date: 2026-09-02 12:34:36.618750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88de4d07461'
down_revision: Union[str, Sequence[str], None] = '673f5a6a4e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_templates',
    sa.Column('type', sa.Enum('GDPR', 'RISC_PRET', name='consent_type'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    # nullable=True + backfill + NOT NULL, ca să nu pice pe rânduri existente în
    # consents (create_type=False fiindcă enum-ul 'consent_type' a fost deja creat
    # de create_table de mai sus, în aceeași migrare).
    consent_type_enum = sa.Enum('GDPR', 'RISC_PRET', name='consent_type', create_type=False)
    op.add_column('consents', sa.Column('type', consent_type_enum, nullable=True))
    op.execute("UPDATE consents SET type = 'GDPR' WHERE type IS NULL")
    op.alter_column('consents', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consents', 'type')
    op.drop_table('consent_templates')
    # ### end Alembic commands ###
