"""drop therapy sessions_included

Revision ID: f8b83e9a0b2a
Revises: a8e7baf64f51
Create Date: 2026-09-02 20:02:16.491164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b83e9a0b2a'
down_revision: Union[str, Sequence[str], None] = 'a8e7baf64f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapies', 'sessions_included')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapies', sa.Column('sessions_included', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
